[from-internal]

; Echo Test
exten => 998,1,NoOp(Echo Test Başladı)
same => n,Answer()
same => n,Wait(1)
same => n,Echo()
same => n,Hangup()

; AI Bot
exten => 999,1,NoOp(AI Bot Başladı)
same => n,Answer()
same => n,Wait(1)
same => n,AGI(/app/bot.py)
same => n,Hangup()
