; === TRANSPORT (UDP) ===
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=145.223.97.228
external_signaling_address=145.223.97.228
local_net=10.0.0.0/8
local_net=172.16.0.0/12
local_net=192.168.0.0/16

; === ENDPOINT 1001 ===
[1001]
type=endpoint
context=from-internal
transport=transport-udp
auth=1001
aors=1001
identify_by=username
disallow=all
allow=ulaw
allow=alaw
allow=gsm
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
ice_support=no
media_encryption=no

[1001]
type=auth
auth_type=userpass
username=1001
password=Guvenli123!

[1001]
type=aor
max_contacts=5
qualify_frequency=60
